# Assigment 1

Juan Navarro, <jsnavarroa@unal.edu.co>

## 1.

| Tutorial                    | Kaggle        |
| :-------------:             |:-------------:| 
| ![title](img/tutorial1.png) | ![title](img/submission1.png) |

## 2.


In [37]:
import numpy as np

TD=np.array([(2, 3, 0, 3, 7),
            (0, 5, 5, 0, 3),
            (5, 0, 7, 3, 3),
            (3, 1, 0, 9, 9),
            (0, 0, 7, 1, 3),
            (6, 9, 4, 6, 0)])

L=np.array([5,
            2,
            3,
            6,
            4,
            3])

m = TD.shape[0]
n = TD.shape[1]

print(TD.shape)
print(L.shape)

(6, 5)
(6,)


### 2.a 


\begin{equation*}
\large
P(T, D)_{m_{x}n} = P(D) P(T | D)_{m_{x}n}    
\end{equation*}

\begin{equation*}
\large
P(T, D)_{m_{x}n} = \frac{1}{n}* TD \oslash \lgroup TD^T * \textbf{1}_{n_{x}1} * \textbf{1}_{n_{x}1} \rgroup ^T
\end{equation*}


In [38]:
a = np.matmul(TD.T, np.ones((m, 1)))
a = np.matmul(a, np.ones((1, m)))

b = TD / a.T

pTD = (1/n)*b

print(np.sum(pTD))

pTD

1.0


array([[0.025     , 0.03333333, 0.        , 0.02727273, 0.056     ],
       [0.        , 0.05555556, 0.04347826, 0.        , 0.024     ],
       [0.0625    , 0.        , 0.06086957, 0.02727273, 0.024     ],
       [0.0375    , 0.01111111, 0.        , 0.08181818, 0.072     ],
       [0.        , 0.        , 0.06086957, 0.00909091, 0.024     ],
       [0.075     , 0.1       , 0.03478261, 0.05454545, 0.        ]])

### 2.b


\begin{equation*}
\large
P(T | D)_{m_{x}n} = TD \oslash \lgroup TD^T * \textbf{1}_{n_{x}1} * \textbf{1}_{n_{x}1} \rgroup ^T
\end{equation*}


In [39]:
a = np.matmul(TD.T, np.ones((m, 1)))
a = np.matmul(a, np.ones((1, m)))

pTgivenD = TD / a.T

pTgivenD

array([[0.125     , 0.16666667, 0.        , 0.13636364, 0.28      ],
       [0.        , 0.27777778, 0.2173913 , 0.        , 0.12      ],
       [0.3125    , 0.        , 0.30434783, 0.13636364, 0.12      ],
       [0.1875    , 0.05555556, 0.        , 0.40909091, 0.36      ],
       [0.        , 0.        , 0.30434783, 0.04545455, 0.12      ],
       [0.375     , 0.5       , 0.17391304, 0.27272727, 0.        ]])

## 2.d


\begin{equation*}
\large
P(D)_{} = \frac{1}{n} * \textbf{1}_{n_{x}1}
\end{equation*}

In [40]:
pD = [1/n] * np.ones((n, 1))

pD

array([[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]])

## 2.f


\begin{equation*}
\large
E[l] = \sum_{i} l_i P(l_i) = \frac{1}{m} * L * \textbf{1}_{m_{x}1}
\end{equation*}

In [41]:
E = (1/m) * L.dot(np.ones((m,1)))
E

array([3.83333333])

## 2.f


\begin{equation*}
\large
B = L - \mu \\
\large
Var[l] = E[(l-\mu)^2] = \frac{1}{m} * (B \circ B) * \textbf{1}_{m_{x}1}
\end{equation*}

In [42]:
b = np.power((L-np.mean(L)), 2)

print(b)

b = L-np.mean(L)
# Hadamard product
b = np.multiply(b, b)

print(b)

var = (1/m) * b.dot(np.ones((m,1)))

var

[1.36111111 3.36111111 0.69444444 4.69444444 0.02777778 0.69444444]
[1.36111111 3.36111111 0.69444444 4.69444444 0.02777778 0.69444444]


array([1.80555556])